# Generated by Django 4.0.2 on 2022-04-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(blank=True, max_length=300, null=True)),
                ('client_number', models.CharField(blank=True, max_length=300, null=True)),
                ('loan_account_number', models.CharField(blank=True, max_length=300, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=300, null=True)),
                ('center_id', models.CharField(blank=True, max_length=300, null=True)),
                ('center_name', models.CharField(blank=True, max_length=300, null=True)),
                ('edo_id', models.CharField(blank=True, max_length=300, null=True)),
                ('edo_name', models.CharField(blank=True, max_length=300, null=True)),
                ('product_id', models.CharField(blank=True, max_length=300, null=True)),
                ('client_name', models.CharField(blank=True, max_length=300, null=True)),
                ('co_borrower_name', models.CharField(blank=True, max_length=300, null=True)),
                ('disbursed_loan_amount', models.CharField(blank=True, max_length=300, null=True)),
                ('loan_date', models.CharField(blank=True, max_length=300, null=True)),
                ('repayment_frequency', models.CharField(blank=True, max_length=300, null=True)),
                ('no_of_installments', models.CharField(blank=True, max_length=300, null=True)),
                ('no_of_instalment_remain', models.CharField(blank=True, max_length=300, null=True)),
                ('first_payment_date', models.CharField(blank=True, max_length=300, null=True)),
                ('installment_amount', models.CharField(blank=True, max_length=300, null=True)),
                ('instalment_type', models.CharField(blank=True, max_length=300, null=True)),
                ('interest_rate', models.CharField(blank=True, max_length=300, null=True)),
                ('maturitydate', models.CharField(blank=True, max_length=300, null=True)),
                ('total_principal_due_amount', models.CharField(blank=True, max_length=300, null=True)),
                ('total_interest_due_amount', models.CharField(blank=True, max_length=300, null=True)),
                ('principal_os_amount', models.CharField(blank=True, max_length=300, null=True)),
                ('interest_os_amount', models.CharField(blank=True, max_length=300, null=True)),
                ('insurance', models.CharField(blank=True, max_length=300, null=True)),
                ('loan_cycle', models.CharField(blank=True, max_length=300, null=True)),
                ('total_principal', models.CharField(blank=True, max_length=300, null=True)),
                ('total_interest', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
